Init simpleAnimationJs
Competec/simple-animation-js pull request #1
Opened 2018-10-25 16:15 UTC by RaphaelHaettich

2018-10-26 09:25 UTC, mfc3370 requested changes
Du weisst doch, dass du mit jsdoc README Files generieren kannst. Denn die Kommentare mit `// Schiess mich tot` ist nicht super hilfreich, weil normalerweise schauen über 90% der Nutzer die Codes von Plugins nicht an, sondern fokussieren sich auf README, um die Nützung zu erfahren.

Ich würde auch vorschlagen ein Debug-Flag mit zu geben, wo wichtige Events alles geloggt wird, wie `Applied Animation: "xyz"`

2018-10-26 09:25 UTC, mfc3370 commented on simpleAnimation.js
> +    animations.forEach((animation) => {
Es wurde nicht validiert und bei falscher Aufruf (`animations === undefined` oder `!== Array`) ist die Seite 💥 !

2018-10-26 09:25 UTC, mfc3370 commented on simpleAnimation.js
> +    const msToSeconds = value => `${value / 1000}s`;
Ich schlage vor diese libs nach draussen zu verschieben, denn die sind kontext-unabhängig.

2018-10-26 09:25 UTC, mfc3370 commented on simpleAnimation.js
> +    // Define Variables
Ich wurde gleich zu Beginn Parameter ohne Fallback validieren und hier gleich die Ausführung einstellen mit Feedback.

2018-11-15 14:46 UTC, mfc3370 approved these changes

2018-11-20 09:37 UTC, FloEberle approved these changes
merci für die erklärung :)

2018-11-20 09:39 UTC, merged